### ISSUE TITLE
Please explain.

### ISSUE THREAD

**Issue by mcgeo52** [vimeo/vimeo.py#138]
I run the following:

```
import vimeo

v = vimeo.VimeoClient(
    token='my token',
    key='my key', 
    secret='my secret'
)

# Make the request to the server for the "/me" endpoint.
about_me = v.get('/me')

# Make sure we got back a successful response.
assert about_me.status_code == 200

try:
    # `scope` is an array of permissions your token needs to access.
    # You can read more at https://developer.vimeo.com/api/authentication#supported-scopes
    token = v.load_client_credentials('my token')

    # usable access token
    print 'token=%s' % token
except vimeo.auth.GrantFailed:
    # Handle the failure to get a token from the provided code and redirect.

    video_uri = v.upload(
        '/home/mktg_bygeo/renders/proj0001/181006geo.m4v',
        data={'name': 'For Geo.', 'description': 'http://mktg.bygeo.biz'}
    )
    print(video_uri)
```

What I get back is:
token=[[REDACTED]]

If I rerun the script, it generates a different token.

Please explain:
1) Why do I need to put my token in both lines 4 and 18?
2) Why am I generating another token if the one I used in both lines 4 and 18 apparently worked well enough to generate a second token (printed per line 21)?
3) Why is the video not uploading per line 25?
4) How much of this is really necessary for a simple pull upload?  I ask this in light of the comment:
"Unauthenticated API requests must generate an access token. You should not generate a new access token for each request. Instead, request an access token once and use it forever."

**Comment by erunion** [comment]
> * Why do I need to put my token in both lines 4 and 18?
> * Why am I generating another token if the one I used in both lines 4 and 18 apparently worked well enough to generate a second token (printed per line 21)?

If you already have a token you don't need to request another. 

Also your `v.load_client_credentials('my token')` isn't right, and you should be passing a list of scopes instead of a token there. Client credentials tokens are unauthenticated, so you wouldn't be able to upload a video with one either.

> Why is the video not uploading per line 25?

Are you receiving any errors? Why are you doing the upload within a try-catch for `vimeo.auth.GrantFailed`?

> How much of this is really necessary for a simple pull upload? I ask this in light of the comment:
"Unauthenticated API requests must generate an access token. You should not generate a new access token for each request. Instead, request an access token once and use it forever."

If you already have a token that's been authenticated to a user, you can simply do:

```python
v = vimeo.VimeoClient('my token')
video_uri = v.upload(...)
```

Additionally, I've redacted your token from your post. A token in the wild can give anybody access to your account. Please treat them as you would the keys to your house.

**Comment by mcgeo52** [comment]
You say:
If you already have a token that's been authenticated to a user, you can simply do:

v = vimeo.VimeoClient('my token')
video_uri = v.upload(...)

That is not he entire script, obviously.

What else is necessary for a simple pull upload?

**Comment by mcgeo52** [comment]
@tommypenner thanks for the question. I had been granted tokens, etc. and assumed I had been granted upload access. Buried in the fine print I found a notice that I needed to edit and resubmit my application.

Assuming that upload access is granted, what Python code will I need? Should what I have above work, or will I need something else?

**Comment by gabrielgisoldo** [comment]
@mcgeo52 , after you get your token, you can use this to upload:
``
v = vimeo.VimeoClient(token=your_token)
``
``
v.upload(path_to_file, data={'name': 'Video title', 'description': '...'})
``
That's all you'll need.

**Comment by mcgeo52** [comment]
Thank you, @gabrielgisoldo.

**Comment by mcgeo52** [comment]
@gabrielgisoldo, it works (after I generated the proper token). Thanks again.

**Comment by Aniket-Singla** [comment]
I am also getting the same error even after getting the required permission.
