### ISSUE TITLE
Vimeo hls url keeps changing

### ISSUE THREAD

**Issue by augmetic** [vimeo/vimeo.py#151]
I am getting the m3u8 URL by making this request with API
https://player.vimeo.com/video/<video_id>/config

This streaming URL is then saved to my database and used in an android app to be played. However, It has come to my attention that these URLs are not permanent and keeps changing. Any way I could get permanent streaming link for my videos? I am a pro user.

**Comment by jaylinski** [comment]
I don't think Vimeo will do this, since they rely on external CDNs to store their videos.

You already have a permanent link: `/video/<video_id>`   
The only thing you have to do is to resolve the link on-demand with the API endpoint you mentioned. Advantage: you can choose to either play a HLS stream or a MP4 file, even if the video-URL is already stored in your database.

**Comment by fisherinnovation** [comment]
@jaylinski is correct, these values will not be static. Best to make the call to get the URL when you need it.

**Comment by Maikhaa** [comment]
These URLs are meant not to be static. You can either make a call every time you want to use them or get access to static URLs by getting one of their paid accounts https://vimeo.zendesk.com/hc/en-us/articles/224823567-Direct-links-to-video-files.
